modid = "hexcasting"
book = "hexcasting:thehexbook"
default_lang = "en_us"

resource_dirs = [  # top takes priority
    # ENABLE reexporting here, because this path is not actually within the hexdoc package
    # we just use the same path to make it easier for translators to find the lang files
    "src/hexdoc/_export/resources",

    "{_common.src}/main/resources",
    "{_common.src}/generated/resources",
    "{_fabric.src}/main/resources",
    "{_fabric.src}/generated/resources",
    "{_forge.src}/main/resources",
    "{_forge.src}/generated/resources",
]
# this is running in a subdirectory checked out by Actions, hence the weird relative path
export_dir = "../../doc/src/hexdoc/_export/generated"

# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"='HexPattern\.fromAngles\("(?P<signature>[qweasd]+)", HexDir\.(?P<startdir>\w+)\),\s*modLoc\("(?P<name>[^"]+)"\)[^;]+?(?:makeConstantOp|Op\w+|Widget\.\w+)(?:[^;]*(?P<is_per_world>true)\);)?' }


[[pattern_stubs]]
path = "{^_common.package}/common/casting/RegisterPatterns.java"
regex = "{^_pattern_regex}"

[[pattern_stubs]]
path = "{^_common.package}/interop/pehkui/PehkuiInterop.java"
regex = "{^_pattern_regex}"

[[pattern_stubs]]
path = "{^_fabric.package}/interop/gravity/GravityApiInterop.java"
regex = "{^_pattern_regex}"


[template]
static_dir = "static"
include = [
    "hexcasting",
    "patchouli",
]

[template.args]
mod_name = "Hex Casting"
author = "petrak@, Alwinfy"
icon_href = "logo.png"
show_landing_text = true


# platforms

[_common]
src = "../Common/src"
package = "{src}/main/java/at/petrak/hexcasting"

[_fabric]
src = "../Fabric/src"
package = "{src}/main/java/at/petrak/hexcasting/fabric"

[_forge]
src = "../Forge/src"
package = "{src}/main/java/at/petrak/hexcasting/forge"
